2025-03-22 19:16:44,423 DEBUG    root            Loaded Command Group: ['gcloud', 'projects']
2025-03-22 19:16:44,426 DEBUG    root            Loaded Command Group: ['gcloud', 'projects', 'create']
2025-03-22 19:16:44,427 DEBUG    root            Running [gcloud.projects.create] with arguments: [--name: "Jarvis", PROJECT_ID: "jarvis-20250322"]
2025-03-22 19:16:44,442 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2025-03-22 19:16:44,697 DEBUG    urllib3.connectionpool https://cloudresourcemanager.googleapis.com:443 "POST /v1/projects?alt=json HTTP/11" 200 None
2025-03-22 19:16:44,700 INFO     ___FILE_ONLY___ Create in progress for [https://cloudresourcemanager.googleapis.com/v1/projects/jarvis-20250322].

2025-03-22 19:16:44,701 INFO     ___FILE_ONLY___ Waiting for [operations/create_project.global.7729478194347254810] to finish...
2025-03-22 19:16:45,719 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2025-03-22 19:16:45,898 DEBUG    urllib3.connectionpool https://cloudresourcemanager.googleapis.com:443 "GET /v1/operations/create_project.global.7729478194347254810?alt=json HTTP/11" 200 None
2025-03-22 19:16:45,900 DEBUG    root            (gcloud.projects.create) Operation [create_project.global.7729478194347254810] failed: 7: Permission 'resourcemanager.projects.create' denied on parent resource 'organizations/703967796528'.
Traceback (most recent call last):
  File "/Users/aarushagarwal/Downloads/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 981, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aarushagarwal/Downloads/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 934, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aarushagarwal/Downloads/google-cloud-sdk/lib/surface/projects/create.py", line 167, in Run
    create_op = operations.WaitForOperation(create_op)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aarushagarwal/Downloads/google-cloud-sdk/lib/googlecloudsdk/api_lib/resource_manager/operations.py", line 83, in WaitForOperation
    return retryer.RetryPollOperation(poller, operation)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aarushagarwal/Downloads/google-cloud-sdk/lib/googlecloudsdk/api_lib/resource_manager/operations.py", line 118, in RetryPollOperation
    return self._Retryer().RetryOnResult(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aarushagarwal/Downloads/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 239, in RetryOnResult
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aarushagarwal/Downloads/google-cloud-sdk/lib/googlecloudsdk/api_lib/resource_manager/operations.py", line 119, in <lambda>
    lambda: operation_poller.Poll(operation),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aarushagarwal/Downloads/google-cloud-sdk/lib/googlecloudsdk/api_lib/resource_manager/operations.py", line 155, in Poll
    raise OperationFailedException(latest)
googlecloudsdk.api_lib.resource_manager.operations.OperationFailedException: Operation [create_project.global.7729478194347254810] failed: 7: Permission 'resourcemanager.projects.create' denied on parent resource 'organizations/703967796528'.
2025-03-22 19:16:45,905 ERROR    root            (gcloud.projects.create) Operation [create_project.global.7729478194347254810] failed: 7: Permission 'resourcemanager.projects.create' denied on parent resource 'organizations/703967796528'.
